CREATE TABLE tbl_group
(
	id INTEGER NOT NULL PRIMARY KEY AUTO_INCREMENT,
	name VARCHAR(128) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

CREATE TABLE tbl_category
(
	id INTEGER NOT NULL PRIMARY KEY AUTO_INCREMENT,
	name VARCHAR(128) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

CREATE TABLE tbl_status
(
	id INTEGER NOT NULL PRIMARY KEY AUTO_INCREMENT,
	name VARCHAR(128) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

CREATE TABLE tbl_user
(
	id INTEGER NOT NULL PRIMARY KEY AUTO_INCREMENT,
	name VARCHAR(128) NOT NULL,
	group_id INTEGER,
	password VARCHAR(128) NOT NULL,
	role VARCHAR(128) NOT NULL,
	login VARCHAR(128) NOT NULL,
	avatar VARCHAR(128) NOT NULL,
	CONSTRAINT FK_user_group FOREIGN KEY (group_id)
		REFERENCES tbl_group (id) ON DELETE SET NULL ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

CREATE TABLE tbl_call
(
	id INTEGER NOT NULL PRIMARY KEY AUTO_INCREMENT,
	name VARCHAR(128) NOT NULL,
	group_id INTEGER,
	category_id INTEGER,
	ip VARCHAR(16) NOT NULL,
	txt TEXT,
	office VARCHAR(128) NOT NULL,
	create_time INTEGER,
	update_time INTEGER,
	status_id INTEGER,
	CONSTRAINT FK_call_group FOREIGN KEY (group_id)
		REFERENCES tbl_group (id) ON DELETE SET NULL ON UPDATE CASCADE,
	CONSTRAINT FK_call_category FOREIGN KEY (category_id)
		REFERENCES tbl_category (id) ON DELETE SET NULL ON UPDATE CASCADE,
	CONSTRAINT FK_call_status FOREIGN KEY (status_id)
		REFERENCES tbl_status (id) ON DELETE SET NULL ON UPDATE CASCADE	
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

CREATE TABLE tbl_comment
(
	id INTEGER NOT NULL PRIMARY KEY AUTO_INCREMENT,
	user_id INTEGER,
	call_id INTEGER NOT NULL,
	create_time INTEGER,
	status_id INTEGER,
	txt TEXT,
	`public` int(11) NOT NULL DEFAULT '0',
	CONSTRAINT FK_comment_status FOREIGN KEY (status_id)
		REFERENCES tbl_status (id) ON DELETE SET NULL ON UPDATE CASCADE,
	CONSTRAINT FK_comment_call FOREIGN KEY (call_id)
		REFERENCES tbl_call (id) ON DELETE CASCADE ON UPDATE CASCADE,
	CONSTRAINT FK_comment_user FOREIGN KEY (user_id)
		REFERENCES tbl_user (id) ON DELETE SET NULL ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

CREATE TABLE tbl_task
(
	id INTEGER NOT NULL PRIMARY KEY AUTO_INCREMENT,	
	user_id INTEGER,
	title VARCHAR(128) NOT NULL,
	txt TEXT,
	create_time INTEGER,
	update_time INTEGER,
	status_id INTEGER,
	CONSTRAINT FK_task_user FOREIGN KEY (user_id)
		REFERENCES tbl_user (id) ON DELETE SET NULL ON UPDATE CASCADE,
	CONSTRAINT FK_call_status FOREIGN KEY (status_id)
		REFERENCES tbl_status (id) ON DELETE SET NULL ON UPDATE CASCADE	
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

CREATE TABLE tbl_taskcomment
(
	id INTEGER NOT NULL PRIMARY KEY AUTO_INCREMENT,
	user_id INTEGER,
	task_id INTEGER NOT NULL,
	create_time INTEGER,
	status_id INTEGER,
	txt TEXT,
	CONSTRAINT FK_taskcomment_status FOREIGN KEY (status_id)
		REFERENCES tbl_status (id) ON DELETE SET NULL ON UPDATE CASCADE,
	CONSTRAINT FK_taskcomment_task FOREIGN KEY (task_id)
		REFERENCES tbl_task (id) ON DELETE CASCADE ON UPDATE CASCADE,
	CONSTRAINT FK_taskcomment_user FOREIGN KEY (user_id)
		REFERENCES tbl_user (id) ON DELETE SET NULL ON UPDATE CASCADE	
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

CREATE TABLE tbl_newcall
(
	id INTEGER NOT NULL PRIMARY KEY AUTO_INCREMENT,
	user_id INTEGER,
	call_id INTEGER,
	CONSTRAINT FK_newcall_user FOREIGN KEY (user_id)
		REFERENCES tbl_user (id) ON DELETE SET NULL ON UPDATE CASCADE,
	CONSTRAINT FK_newcall_call FOREIGN KEY (call_id)
		REFERENCES tbl_call (id) ON DELETE SET NULL ON UPDATE CASCADE	
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;